# PostgreSQL DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/Ecom
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8082
# enabling all spring boot actuator endpoints
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true
info.app.name=E-Commerce App
info.app.description=Backend for online shopping
info.app.version=1.0.0

# Hibernate Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optional but useful
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
